# -----------------------------------------------------------------------------
# UI Deployment for Uptime Monitor
# -----------------------------------------------------------------------------
#
# Nuon template variables used in this manifest:
#
#   Container Image (from docker_build component):
#     {{ .nuon.components.ui_image.outputs.image.repository }}
#     {{ .nuon.components.ui_image.outputs.image.tag }}
#
# -----------------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          # Image built by Nuon docker_build component (0-ui-image.toml)
          image: "{{ .nuon.components.ui_image.outputs.image.repository }}:{{ .nuon.components.ui_image.outputs.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 32Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: ui
