apiVersion: v1
kind: Namespace
metadata:
  name: headlamp
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: headlamp
  namespace: headlamp
  labels:
    k8s-app: headlamp
---
apiVersion: v1
kind: Secret
metadata:
  name: headlamp-admin
  namespace: headlamp
  labels:
    k8s-app: headlamp
  annotations:
    kubernetes.io/service-account.name: "headlamp"
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headlamp-admin
  labels:
    k8s-app: headlamp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: headlamp
    namespace: headlamp
