---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "headlamp-{{.nuon.install.id}}"
  namespace: headlamp
  labels:
    app.nuon.co/name: headlamp
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - "headlamp-{{.nuon.install.id}}"
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: headlamp
                port:
                  number: 80
